# Generated by Django 5.1.1 on 2024-09-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='AccountProfile',
        ),
    ]
