# Generated by Django 5.1.1 on 2024-09-25 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_account_accountprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, default=1),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='email',
            field=models.EmailField(default='user@info.com', max_length=254),
        ),
    ]
