# Generated by Django 5.1.1 on 2024-09-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_accountprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='username',
            field=models.CharField(default='test-user', max_length=50),
            preserve_default=False,
        ),
    ]
