[phases.setup]
nixPkgs = ["...", "file", "zlib"] 

[env]
LD_LIBRARY_PATH = "${file}/lib:${libmagic}/lib:$LD_LIBRARY_PATH"


[phases.build]
commands = [
  "...",
  "echo START DEBUG Library Path: $LD_LIBRARY_PATH",
  "echo Searching for libmagic.so:",
  "find / -name 'libmagic.so*' 2>/dev/null | head -n 10",  
  "echo File Command Version:",
  "file --version",
  "echo File Command Library Dependencies:",
  "ldd $(which file)",
  "echo Python Module Search Paths:",
  "python -c \"import sys; print('\\n'.join(sys.path))\"",
  "echo Magic Library Location:",
  "python -c \"import ctypes.util; print(ctypes.util.find_library('magic'))\""
]
