# Generated by Django 5.1.1 on 2024-10-07 15:46

import datetime
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_rename_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=3000)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/globalContent/', verbose_name='Image')),
                ('created_at', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
