# Generated by Django 5.1.1 on 2024-10-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsitecontent',
            name='slug',
            field=models.TextField(default='default', max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
