# Generated by Django 5.1.1 on 2024-10-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_globalsitecontent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsitecontent',
            name='slug',
            field=models.TextField(blank=True, max_length=120, unique=True),
        ),
    ]
