# Generated by Django 5.1.1 on 2024-11-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_globalsitecontent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsitecontent',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='globalContent/'),
        ),
    ]
