# Generated by Django 5.1.1 on 2024-11-27 19:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_globalsitecontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsitecontent',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
