# Generated by Django 5.1.1 on 2024-10-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccountprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
