# Generated by Django 5.1.1 on 2024-10-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountprofile', '0002_alter_customaccountprofile_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customaccountprofile',
            managers=[
            ],
        ),
    ]
