# Generated by Django 5.1.1 on 2024-09-16 16:13

import datetime
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/testimagemodel/', verbose_name='Image')),
                ('description', models.TextField(default='The Product Description is here')),
                ('created_at', models.TimeField(default=datetime.datetime.now)),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=6)),
                ('category', models.ManyToManyField(to='product.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
